name: Release Pipeline

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  php-lint-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Lint PHP (syntax check)
        run: |
          echo "Linting PHP files..."
          ! find . -type f -name "*.php" -print0 | xargs -0 -I{} php -l "{}" | grep "Errors parsing"

      # Descomenta si usas Composer y PHPUnit
      # - name: Install dependencies
      #   run: composer install --no-interaction --no-progress
      # - name: Run tests (PHPUnit)
      #   run: vendor/bin/phpunit --testdox

      - name: Archive artifact (opcional)
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: .
          retention-days: 7

  create-github-release:
    needs: php-lint-and-tests
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Read version from tag
        id: ver
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.ver.outputs.version }}
          name: Release ${{ steps.ver.outputs.version }}
          body: |
            Release generado automáticamente por GitHub Actions.
            Consulta CHANGELOG.md para las notas de versión.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-simulado:
    needs: create-github-release
    runs-on: ubuntu-latest
    steps:
      - name: Simular despliegue
        run: echo "Despliegue simulado OK a producción."
